### PR TITLE
Handle mismatched nodenames when setting NetworkUnavailable

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

Still need to add a test, but this is probably the right fix.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Fix that calico/node would fail to set NetworkUnavailable to false for etcd clusters with mismatched nodenames
```

### CODE REVIEW

**Comment by bcreane** [comment]
🎉

**Review by song-jiang — APPROVED** [review]
LGTM

**Comment by bcreane** [comment]
@caseydavenport - wdyt about cherry-picking into earlier Calico releases? I think @mgleung is planning releases as far back as v3.13.

**Comment by caseydavenport** [comment]
> planning releases as far back as v3.13.

:grimacing: 

It's an easy and straighforward cherry-pick.

**Comment by caseydavenport** [comment]
@bcreane cherry-picked back to v3.15

**Pull request merged**
