### PR TITLE
Add missing env SVDIR for sv

### PR DESCRIPTION
**Pull request by halfcrazy**
https://github.com/projectcalico/confd/issues/400

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
On non-AMD64 platforms, fix that confd was unable to restart bird.
```

### CODE REVIEW

**Review by fasaxc — APPROVED** [review]
LGTM

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Comment by halfcrazy** [comment]
What's wrong with ci, I cannot see the details.

**Comment by fasaxc** [comment]
Semaphore isn't picking up the PR; I have raised a ticket with them

**Pull request merged**
