### PR TITLE
Add non-mutating cni-conf-dir and cni-bin-dir defaulting to config.ps1

### PR DESCRIPTION
**Pull request by jayunit100**
a fix for #1062  (we can make install-calico.ps1 modular in a later PR if we want to)

### CODE REVIEW

**Review by song-jiang — CHANGES_REQUESTED** [review]
Thanks for your PR @jayunit100 . 

The purpose of `config.ps1` is a single file which holds all configuration items for Calico Windows. If user want to update any item, they can easily do so by just replace the line for the item. e.g. $env:ETCD_CERT_FILE = "<your etcd cert>". 

Calico installation script is the example of that practise. On different cloud platforms, it replaces related configuration items. 

This one-config-one-line approach leaves config logic to the user. It also helps debugging as `config.ps` holds all the values.

**Comment by song-jiang** [comment]
@lmm I just notices that there are extra line of `CNI-CONF_DIR` for containerd. Maybe we should move this out to Calico installation script in order to keep one-config-one-line?

**Comment by jayunit100** [comment]
``` If user want to update any item, they can easily do so by just replacing the line for the item. e.g. $env:ETCD_CERT_FILE = "".``` 

really ? hmmm can we add an override functionality into this file to read from env vars so that we dont have to overwrite the whole thing ?

**Comment by song-jiang** [comment]
I know it looks dumb to replace the whole string. But it makes config.ps1 simple to read and if user hit any issue, they can simply check the file to get all the values.

**Comment by caseydavenport** [comment]
@song-jiang @jayunit100 what's the next step on this PR?

**Comment by jayunit100** [comment]
i guess we should discuss at the community meeting ?   It seems to me like we should make this a json file if its not intended to be dynamic , because otherwise its tricky for end users to envision editing powershell as a configuration file, esp as we move to priveliged containers / pods running CNIs in 1.23+

**Comment by song-jiang** [comment]
@jayunit100 Sorry I couldn't attend community meeting due to a conflict. As for your suggestion of using a json file, the fact is all Calico components (felix, node) reads Env variables for configurations. A json file means there are extra steps required (converting json to env) for each Calico component.

**Comment by song-jiang** [comment]
With privileged container, we would set configurations through FELIX_CONFIG parameters for the daemonset hence config.ps1 could be removed completely.

**Comment by caseydavenport** [comment]
Sounds like daemonset install with privileged containers support is the way forward - then we get k8s-native configuration through configmaps and CRDs more easily.

**Comment by caseydavenport** [comment]
Going to close this for now. Acknowledge what is here isn't ideal, though.

**Pull request closed without merging**
