### PR TITLE
added armhf architecture support

### PR DESCRIPTION
**Pull request by aalaesar**
## Description

- **new feature** : add armv7 support for the component
- this is one of the many PR needed for adding armhf support for calico (see issue [calico:3583](https://github.com/projectcalico/calico/issues/3583))
- The image built have been tested locally on a k8s cluster composed of  6 raspberry pi 2&3b

## Requirements:

The following PR must be merged prior to this PR:

- [x]  [bird](https://github.com/projectcalico/bird/pull/89)
- [x]  [go-build](https://github.com/projectcalico/go-build/pull/211)
- [x] ~~[bpftool](https://github.com/projectcalico/bpftool/pull/4)~~

## Todos

- [ ] Tests
- [ ] Release note

## Release Note

```release-note
- Add armhf Build
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
@aalaesar same here - Makefile conflicts :'(

**Comment by aalaesar** [comment]
@caseydavenport fixed the conflict
bird and bpftool still need to be merged before this one

**Comment by caseydavenport** [comment]
Looking at those now

**Comment by caseydavenport** [comment]
Both the bpftool and BIRD PRs have been merged now.

I think we'll need @fasaxc to help us with a bpftool release so we can update the referenced image in the Dockerfile.

We will also need to update the BIRD reference once we have a new release, but for now you can probably use `calico/bird:feature-ipinip-armv7`

**Comment by aalaesar** [comment]
@caseydavenport 
Hello, thank you for the merges
How far could be the next bird release ?
if the amrv7 node image uses the feature-ipinip-armv7 tag, will it be merged in master or is it just for CI tests ?

**Comment by caseydavenport** [comment]
> if the amrv7 node image uses the feature-ipinip-armv7 tag, will it be merged in master or is it just for CI tests ?

Actually, I was wrong - think you can change this line: https://github.com/projectcalico/node/blob/6cd4484c894bbcff76fdc7e63449e8ee8f50affe/Makefile#L60-L61

To use this BIRD_VERSION: `v0.3.3-178-g274dc2e1`

and you should be set. We build the latest BIRD continuously.

**Comment by aalaesar** [comment]
> g0a2f8d2d

@caseydavenport 
just updated bird version 
sorry for the delay.
a new bpftool image for armv7  is still required to build node in the calico repository

Regards,
Aal.

**Comment by caseydavenport** [comment]
@aalaesar I think eBPF isn't going to work on ARMv7 anyway right now so maybe for now we can just remove the bpfrool binary from the ARMv7 Dockerfile / image?

That should be enough to get this merged.

**Comment by aalaesar** [comment]
@caseydavenport 
following your answer I checked if eBPF has worked on rapberry pi OS
on the OS perspective, it should be "just" the BPF module needed to be compiled in the kernel.
It seems to be compiled already on raspi OS 32 bits.
```shell
$ zgrep -E "(BPF|XDP)" /proc/config.gz
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
# CONFIG_BPF_PRELOAD is not set
# CONFIG_XDP_SOCKETS is not set
CONFIG_NETFILTER_XT_MATCH_BPF=m
# CONFIG_BPFILTER is not set
# CONFIG_NET_CLS_BPF is not set
# CONFIG_NET_ACT_BPF is not set
# CONFIG_BPF_JIT is not set
# CONFIG_BPF_STREAM_PARSER is not set
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_LIRC_MODE2=y
# CONFIG_NBPFAXI_DMA is not set
CONFIG_BPF_EVENTS=y
# CONFIG_TEST_BPF is not set

$ uname -a
Linux k8s-nod01 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux

$ cat /sys/firmware/devicetree/base/model
Raspberry Pi 3 Model B Rev 1.2
```

I'll look to make some ebpf tests if you think it's relevant.

Regards,
Aal.

**Comment by fasaxc** [comment]
We disable eBPF on non-amd64 platforms; the BPF programs haven't been ported to those platforms yet.  They _may_ just work on ARM64 but definitely not on PPC and possibly not on ARM32.

**Comment by aalaesar** [comment]
@fasaxc 
Ok so I removed the bpf tool binary.

**Pull request merged**
