### PR TITLE
[master] Semaphore Auto Pin Update

### PR DESCRIPTION
**Pull request by marvin-tigera**

### CODE REVIEW

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Comment by neiljerram** [comment]
@Brian-McM Hmm, I think I was just about to have this one pass.... https://tigera.semaphoreci.com/workflows/21bf0a94-c60d-44f9-bb38-f83a652dab2c?pipeline_id=1edde1db-db78-4d46-aece-3a4226995f98

**Comment by Brian-McM** [comment]
I think I meant to delete a different one that wasn't running anything... I'm sorry...

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Comment by Brian-McM** [comment]
@neiljerram looks look re opening still ties it to the running semaphore job I think I've undone my mistake. Sorry again.

**Comment by neiljerram** [comment]
@Brian-McM No worries, and thanks!

**Pull request merged**
